# PROCESSO DE SOFTWARE

## CONCEITO DE PROCESSO, ATIVIDADES E TAREFAS

No mundo dos negócios como é conceituado um processo ?

> *Um PROCESSO é um conjunto de atividades que são executadas para atingir um objetivo* (Business Process Model and Notation - BPMN)
>
> *ATIVIDADES são os trabalhos que devem ser realizados para que um processo seja executado* (Business Process Model and Notation - BPMN)
>
> *TAREFAS são decomposições de atividades e representam um conjunto de passos ou ações executadas para realizar um trabalho. Essas tarefas logicamente relacionadas quando encadeadas completam a atividade.* (Business Process Model and Notation - BPMN)

## O PROCESSO DE SOFTWARE

> *PROCESSO DE SOFTWARE é uma metodologia que define as atividades necessárias para desenvolver um software de qualidade* (Roger S Pressman)

> *PROCESSO DE SOFTWARE é um conjunto de atividades que visam a produção de um software* (Ian Sommerville)

## ATIVIDADES FUNDAMENTAIS DE UM PROCESSO DE SOFTWARE

**POR QUAIS ATIVIDADES VOCÊ (NECESSÁRIAMENTE) PASSA ?**

+--------------+--------------+--------------+--------------+--------------+
| ATIVIDADE #1 | ATIVIDADE #2 | ATIVIDADE #3 | ATIVIDADE #4 | ATIVIDADE #5 |
+==============+==============+==============+==============+==============+
| comunicação  | planejamento | modelagem    | construção   | entrega      |
+--------------+--------------+--------------+--------------+--------------+

: PROCESSO DE SOFTWARE - ATIVIDADES - PRESSMAN

+---------------+--------------+---------------+--------------+--------------+
| ATIVIDADE #1  | ATIVIDADE #2 | ATIVIDADE #3  | ATIVIDADE #4 | ATIVIDADE #5 |
+===============+==============+===============+==============+==============+
| especificação | projeto      | implementação | validação    | evolução     |
+---------------+--------------+---------------+--------------+--------------+

: PROCESSO DE SOFTWARE - ATIVIDADES - SOMMERVILLE

## MODELOS DE PROCESSO DE SOFTWARE

**COMO VOCÊ PASSA POR ESSAS ATIVIDADES ?**

### ABORDAGEM CASCATA

#### VANTAGENS DESSE MODELO

+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---+
| Vantagem                        | Descrição                                                                                                                                  |   |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---+
| Simplicidade                    | -   fácil de entender e implementar;                                                                                                       |   |
|                                 |                                                                                                                                            |   |
|                                 | -   pois possui fases sequenciais bem definidas, com entregas e revisões em cada etapa;                                                    |   |
|                                 |                                                                                                                                            |   |
|                                 | -   facilita o gerenciamento do projeto, especialmente para equipes menores;                                                               |   |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---+
| Documentação                    | -   Natureza estruturada do                                                                                                                |   |
|                                 |                                                                                                                                            |   |
|                                 | -    Exige a produção de documentação completa em cada fase;                                                                               |   |
|                                 |                                                                                                                                            |   |
|                                 | -   Útil para rastrear o progresso, facilitar a comunicação entre as partes;                                                               |   |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---+
| Controle                        | -   maior controle sobre o projeto, escopo, os prazos e os custos são definidos no início e seguidos rigorosamente;                        |   |
|                                 |                                                                                                                                            |   |
|                                 | -   Cliente tenha previsão precisa do resultado final e investimento necessário.;                                                          |   |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---+
| Adequado para projetos estáveis | -   Adequado para projetos com requisitos bem definidos e estáveis e que não devem sofrer muitas alterações ao longo do desenvolvimento.   |   |
+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+---+

#### DESVANTAGENS DESSE MODELO

+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---+
| Desvantagem        | Descrição                                                                                                                                           |   |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---+
| Inflexibilidade    | -   Rigidez. Uma vez que uma fase é concluída, é difícil voltar atrás e fazer alterações.                                                           |   |
|                    |                                                                                                                                                     |   |
|                    | -   problemático se os requisitos mudarem ou se surgirem problemas inesperados                                                                      |   |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---+
| Feedback tardio    | -   O cliente só tem contato com o produto final nas últimas fases do projeto;                                                                      |   |
|                    |                                                                                                                                                     |   |
|                    | -   Difícil identificação de erros ou inadequações;                                                                                                 |   |
|                    |                                                                                                                                                     |   |
|                    | -   Atrasos, custos adicionais e insatisfação do cliente;                                                                                           |   |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---+
| Longos prazos      | -   prazos de entrega mais longos,                                                                                                                  |   |
|                    |                                                                                                                                                     |   |
|                    | -   cada fase precisa ser concluída antes da próxima ser iniciada.                                                                                  |   |
|                    |                                                                                                                                                     |   |
|                    | -   problemático em projetos com restrições de tempo ou em mercados dinâmicos.                                                                      |   |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---+
| Risco de insucesso | Falta de flexibilidade e feedback tardio podem aumentar o risco de o projeto não atender às expectativas do cliente ou às necessidades do mercado.  |   |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---+

### ABORDAGEM INCREMENTAL

### ABORDAGEM RUP

### ABORDAGEM(ENS) ÁGIL(EIS)
